create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  fio text not null,
  dob date not null,
  region text not null,
  district text not null,
  phone text not null,
  email text not null,
  "higherEd" text not null,
  "gradYear" text not null,
  "bachelorFile" text not null,
  "masterFile" text,
  "phdFile" text,
  "langCertFile" text,
  "cvFile" text,
  "statusKey" text not null default 'yangi' check ("statusKey" in ('yangi', 'jarayonda', 'qabul', 'rad')),
  "createdAt" timestamptz not null default now()
);

alter table public.applications enable row level security;

drop policy if exists "public can insert applications" on public.applications;
create policy "public can insert applications"
on public.applications
for insert
to anon
with check (true);

drop policy if exists "public can read applications" on public.applications;
create policy "public can read applications"
on public.applications
for select
to anon
using (true);

drop policy if exists "public can update status" on public.applications;
create policy "public can update status"
on public.applications
for update
to anon
using (true)
with check (true);

