create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  fio text not null,
  dob date not null,
  region text not null,
  district text not null,
  phone text not null,
  email text not null,
  "higherEd" text not null,
  "gradYear" text not null,
  "bachelorFile" text not null,
  "masterFile" text,
  "phdFile" text,
  "langCertFile" text,
  "cvFile" text,
  "statusKey" text not null default 'yangi' check ("statusKey" in ('yangi', 'jarayonda', 'qabul', 'rad')),
  "createdAt" timestamptz not null default now()
);

alter table public.applications enable row level security;

drop policy if exists "public can insert applications" on public.applications;
create policy "public can insert applications"
on public.applications
for insert
to anon
with check (true);

drop policy if exists "public can read applications" on public.applications;
create policy "public can read applications"
on public.applications
for select
to anon
using (true);

drop policy if exists "public can update status" on public.applications;
create policy "public can update status"
on public.applications
for update
to anon
using (true)
with check (true);

-- Vacancies
create table if not exists public.vacancies (
  id bigint generated by default as identity primary key,
  title text not null,
  rate text,
  "salaryMin" numeric,
  "salaryMax" numeric,
  "createdAt" timestamptz not null default now()
);

alter table public.vacancies enable row level security;

drop policy if exists "public can read vacancies" on public.vacancies;
create policy "public can read vacancies"
on public.vacancies
for select
to anon
using (true);

drop policy if exists "public can insert vacancies" on public.vacancies;
create policy "public can insert vacancies"
on public.vacancies
for insert
to anon
with check (true);

drop policy if exists "public can update vacancies" on public.vacancies;
create policy "public can update vacancies"
on public.vacancies
for update
to anon
using (true)
with check (true);

drop policy if exists "public can delete vacancies" on public.vacancies;
create policy "public can delete vacancies"
on public.vacancies
for delete
to anon
using (true);

